name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-14, ubuntu-24.04-arm, macos-13, windows-2022 ]
        build_type: [Release]
        staticcompile: [ON, OFF]
        c_compiler: [gcc]
        cpp_compiler: [g++]

    steps:
    - uses: actions/checkout@v4.1.1

    # install dependencies
    - name: Install boost & help2man for Linux
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get update && sudo apt-get install -yq help2man

    - name: Installing Numpy
      run: |
        pip install pip --upgrade
        pip install numpy lit

    - name: Add git submodules for Linux only (not needed for non-testing)
      if: matrix.os == 'ubuntu-20.04'
      run: git submodule update --init

    - name: Configure CMake for linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_TESTING=ON  -DSTATICCOMPILE=${{ matrix.staticcompile }}
        cmake --build . --config ${{ matrix.build_type }}

    - name: Configure CMake for non-linux
      if: ! contains(matrix.os, 'ubuntu')
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_TESTING=OFF -DSTATICCOMPILE=${{ matrix.staticcompile }}
        cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      run: ctest -C ${{ matrix.build_type }}

    - name: Upload Artifact - Linux x86_64
      if: contains(matrix.os, 'ubuntu') && matrix.staticcompile == 'ON' && !contains(matrix.os, 'arm')
      uses: actions/upload-artifact@v4
      with:
        name: cmsgen-linux-amd64
        path: cmsgen

    - name: Upload Artifact - Linux Arm64
      if: contains(matrix.os, 'ubuntu') && matrix.staticcompile == 'ON' && contains(matrix.os, 'arm')
      uses: actions/upload-artifact@v4
      with:
        name: cmsgen-linux-arm64
        path: cmsgen

    - name: Upload Artifact - Mac Arm64
      if: contains(matrix.os, 'macos') && matrix.staticcompile == 'ON' && matrix.os == 'macos-14'
      uses: actions/upload-artifact@v4
      with:
        name: cmsgen-mac-arm64
        path: cmsgen

    - name: Upload Artifact - Mac x86_64
      if: contains(matrix.os, 'macos') && matrix.staticcompile == 'ON' && matrix.os == 'macos-13'
      uses: actions/upload-artifact@v4
      with:
        name: cmsgen-mac-x86_64
        path: cmsgen

    - name: Upload Artifact - Windows
      if: matrix.os == 'windows-2022' && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: cmsgen-win64.exe
        path: Release\cmsgen.exe
