name: Python package build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine flake8
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a source tarball
      run: >-
        python -m
        build
        --sdist
        --outdir dist/
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1
      with:
        build-requirements: 'cython numpy'
        system-packages: 'zlib-devel boost-devel boost-program-options boost-serialization'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
       name: python-wheel-artifact
       path: dist/*
    - name: Publish tarball to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload --skip-existing --disable-progress-bar dist/pycmsgen-*.tar.gz
